title: "Neoárabe: caminhos da arquitetura árabe no Brasil"
email: palazzo@unb.br
description: >- 
  A composição interdisciplinar e interinstitucional
  deste livro explora a tessitura de influências que
  formam uma imagem da cultura árabe no Brasil marcada
  pelo ecletismo estético, pelo sincretismo de práticas
  culturais e pela ressignificação de argumentos
  históricos assim como de identidades comunitárias.
baseurl: "/neoarabe"
url: "https://dmcpatrimonio.github.io"
# twitter_username: jekyllrb
github_username:  dmcpatrimonio

# Build settings
theme: minima
minima:
  date_format: "%Y-%m-%d"
markdown: kramdown
kramdown:
  auto_ids: true
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-relative-links
source: docs/
relative_links:
  enabled: true
  collections: true
keep_files:
  - reveal.js
permalink: /:categories/:year/:month/:day/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs/reveal.js/
  - README.md
