# General {{{1
title: Neoárabe
email: labeurbe@unb.br
description: >-
  Reminiscências árabes no Brasil moderno
baseurl: "/neoarabe" # the subpath of your site, e.g. /blog
url: "https://dmcpatrimonio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: p3palazzo
github_username:  dmcpatrimonio
open_graph:

# Build settings {{{1
source: docs/
remote_theme: p3palazzo/minima-scholar # {{{2
minima:
  date_format : "%e %B %Y"
  social_links:
    twitter   : https://twitter.com/p3palazzo
    github    : https://github.com/dmcpatrimonio/neoarabe
header_pages:
  - ijia-abstract.md

plugins: # {{{2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Other build parameters {{{2
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: true
  header_offset: 1
  transliterated_header_ids: true
relative_links:
  enabled: true
  collections: true
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# vim: set foldmethod=marker :
