on:
  push:
    branches: [ ijia ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: |
        cd ${{ github.workspace }}
        pip install wheel
        pip install -r requirements.txt
    - name: Setup CSL styles
      run: |
        cd ${{ github.workspace }}
        git submodule add https://github.com/citation-style-language/styles.git
    - name: Convert file
      uses: docker://pandoc/latex:2.9.2.1
      with:
        args: -d spec/pdf.yaml -o ijia-abstract.pdf ijia-abstract.md
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: ijia-abstract
        path: ijia-abstract.pdf
