on:
  push:
    branches: [ ijia ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      run: |
        cd ${{ github.workspace }}
        pip install -r requirements.txt
        sudo apt-get install pandoc pandoc-citeproc
        pandoc --version
        pandoc-citeproc --version
    - uses: actions/checkout@v2
    - name: Setup CSL styles
      run:
        git submodule add https://github.com/citation-style-language/styles.git
    - name: Convert file
      run: |
        cd ${{ github.workspace }}
        make ijia-abstract.pdf
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: ijia-abstract
        path: ${{ github.workspace }}/ijia-abstract.pdf
